version: '3'
services:
  web:
    image: cs411project1app
    ports: 
      - "8000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cs411project1db
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
